name: Twitter Bot Scheduler

on:
  schedule:
     - cron: '0 7 * * *'
     - cron: '0 8 * * *'
     - cron: '0 11 * * *'
     - cron: '0 13 * * *'
     - cron: '0 17 * * *'
     - cron: '0 18 * * *'
     - cron: '0 20 * * *'
     - cron: '0 21 * * *'
     - cron: '0 22 * * *'
     - cron: '0 23 * * *'


  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw tweepy

      - name: Run tweet bot
        run: python bot.py
