name: Twitter Bot Scheduler

on:
  schedule:
     - cron: '0 0 * * *'
     - cron: '0 3 * * *'
     - cron: '0 6 * * *'
     - cron: '0 9 * * *'
     - cron: '0 12 * * *'
     - cron: '0 15 * * *'
     - cron: '0 17 * * *'
     - cron: '0 19 * * *'
     - cron: '0 21 * * *'
     - cron: '0 23 * * *'


  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests emoji

      - name: Run tweet bot
        run: python bot.py

